### ISSUE TITLE
First two arguments are invalid in windows bash environment

### ISSUE THREAD

**Issue by davidwonghk** [xutl-es/args#1]
## Environment:
OS: Windows 10
Shell: Bash (mingw)
Node: v14.15.4

## Descriptoin
eg. this does not work in my environment:
```javascript
//test.js
const { parse, flag } = require('@xutl/args');
const args = parse(process.argv, flag('version'));

node test.js -v
```
The reason is that in my environment the first two arguments passing into `parse` function would be "node" and "test.js"

this works in my environment:
```javascript
//test.js
const { parse, flag } = require('@xutl/args');
const args = parse(process.argv.slice(2), flag('version'));

node test.js -v
```

**Comment by pipobscure** [comment]
Should be fixed in release v1.02
